# configuration for https://cargo-generate.github.io/cargo-generate/

[template]
sub_templates = ["examples/exex/minimal", "examples/node-custom-rpc", "examples/custom-payload-builder"]

[hooks]
#init = [...]
#pre = ["pre-script.rhai"]
post = ["hook.rhai"]